import { transformSheetData } from './transform-sheet-data';
import type { SheetRow } from './transform-sheet-data';

const sheetData: SheetRow[] = [
  {
    Image: '',
    Brand: 'A England',
    Polish: 'Rose Bower',
    Color: 'Red',
    'Finishes/Types': 'Micro Holo Glitter, Shimmer',
    Link: 'http://thepolishwell.blogspot.com/2013/08/a-england-rose-bower-order-of-garter.html',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Arcane Lacquer',
    Polish: 'Engage Within',
    Color: 'Blue',
    'Finishes/Types': 'Shimmer, Duochrome',
    Link: '',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Barry M',
    Polish: 'Mediterranean',
    Color: 'Multi',
    'Finishes/Types': 'Duochrome, Metallic',
    Link: 'https://rainbowifyme.blogspot.com/2015/02/barry-m-pacific-and-mediterranean.html',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Barry M',
    Polish: 'Socialite',
    Color: 'Pink',
    'Finishes/Types': 'Iridescent Glitter, Shimmer, Shifty',
    Link: 'https://nail-lacquer.co.uk/barry-m-glitterati/',
    Coats: '2',
    Rating: 'B+',
    Notes: 'thinned this out but could use more thinner, is probably an A',
  },
  {
    Image: '',
    Brand: 'Barry M',
    Polish: 'Vintage Violet',
    Color: 'Purple',
    'Finishes/Types': 'Creme',
    Link: 'http://www.thevegantaff.com/2015/03/manicure-monday-barry-m-vintage-violet.html',
    Coats: '2',
    Rating: 'A',
    Notes: 'great formula, skinny brush tho',
  },
  {
    Image: '',
    Brand: 'Barry M Gelly Hi-Shine',
    Polish: 'Almond',
    Color: 'Gray',
    'Finishes/Types': 'Creme',
    Link: 'http://www.britnails.co.uk/2014/05/barry-m-gelly-nail-paint-summer-2014.html',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Barry M Gelly Hi-Shine',
    Polish: 'Cardamom',
    Color: 'Green',
    'Finishes/Types': 'Creme',
    Link: 'https://www.britnails.co.uk/2014/08/barry-m-autumnwinter-2014-gelly-nail.html#more',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Barry M Gelly Hi-Shine',
    Polish: 'Green Berry',
    Color: 'Teal',
    'Finishes/Types': 'Creme',
    Link: 'https://primerandtheprincess.blogspot.com/2013/02/new-barry-m-gelly-hi-shine-nail-polish_7916.html',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Essie',
    Polish: 'Wicked',
    Color: 'Red',
    'Finishes/Types': 'Jelly, Mini',
    Link: 'https://nazsnails.blogspot.com/2012/12/essie-wicked.html',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Essie Gel Couture',
    Polish: 'Twill Seeker',
    Color: 'Purple',
    'Finishes/Types': 'Shimmer',
    Link: 'http://nailtastic.blogspot.com/2016/06/essie-twill-seeker.html',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Essie Luxeffects',
    Polish: 'A Cut Above',
    Color: 'Pink',
    'Finishes/Types': 'Chunky Glitter, Topper',
    Link: 'https://thelacquerlounge.blogspot.com/2011/12/essie-cut-above-luxeffects-collection.html',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Essie Luxeffects',
    Polish: 'Rock at the Top',
    Color: 'Gold',
    'Finishes/Types': 'Chunky Glitter, Mini',
    Link: 'http://mylifeinturquoise.blogspot.com/2014/10/essie-luxeffects-2014-rock-at-top.html?m=1',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Essie Luxeffects',
    Polish: 'Set in Stones',
    Color: 'Silver',
    'Finishes/Types': 'Chunky Glitter, Topper',
    Link: 'https://kakinenailart.blogspot.com/2014/02/essie-set-in-stones-luxeffects-2013.html',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Essie Luxeffects',
    Polish: 'Summit of Style',
    Color: 'Gold',
    'Finishes/Types': 'Chunky Glitter, Mini',
    Link: 'http://nailsalwayspolished.blogspot.com/2014/11/essie-summit-of-style.html',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Expressie',
    Polish: 'Notifications On',
    Color: 'Red',
    'Finishes/Types': 'Creme',
    Link: 'https://www.essie.com/nail-polish/quick-dry/reds/notifications-on',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Fancy Gloss',
    Polish: 'Silver Lotus',
    Color: 'Multi',
    'Finishes/Types': 'Thermal, Linear Holo',
    Link: 'https://curbappealnails.blogspot.com/2015/04/chevron-nails-fancy-gloss-silver-lotus-a-england-dorian-gray.html',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Forever 21',
    Polish: 'Grey/Multi',
    Color: 'Gray',
    'Finishes/Types': 'Glitter',
    Link: '',
    Coats: '',
    Rating: '',
    Notes: '',
  },
  {
    Image: '',
    Brand: 'Forever 21',
    Polish: 'Light Blue/Black',
    Color: 'Blue',
    'Finishes/Types': 'Glitter',
    Link: 'https://nailsmydreams.blogspot.com/2015/04/forever-21-speckled-nail-polishes-light.html',
    Coats: '',
    Rating: '',
    Notes: '',
  },
];

// Transform the data
const transformedData = transformSheetData(sheetData);

// Output the result
console.log(JSON.stringify(transformedData, null, 2));
